### ISSUE TITLE
local host url error

### ISSUE THREAD

**Issue by Essi5764** [adrianhajdin/project_medical_pager_chat#3]
client/src/components/Auth.jsx

On line 31 const URL = 'https://localhost:5000/auth';

This generates a network error.

SHOULD BE : const URL = 'http://localhost:5000/auth';

Thanks for an awesome tutorial.

**Comment by nicogulo** [comment]
I got a problem before like that. thank you @Essi5764

**Comment by Muftinet** [comment]
I am still getting network error, please any help. This is the error below. Thanks
Uncaught (in promise) Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:99)

**Comment by nicogulo** [comment]
can you drop the code?

**Comment by Essi5764** [comment]
> I am still getting network error, please any help. This is the error below. Thanks
> Uncaught (in promise) Error: Network Error
> at createError (createError.js:16)
> at XMLHttpRequest.handleError (xhr.js:99)

Hello Muftinet, I tried to find the project on your repo but I cannot get into the folder to see the code. This is how I fixed mine. Go to client folder>src>components>Auth.jsx. Make sure your url is like this: const URL = 'http://localhost:5000/auth';

I can attempt to help you further once I can see your code.

**Comment by vuongthanhtuan** [comment]
I also problem the same. I sure that I fixed URL. Please any help me. 
Uncaught (in promise) Error: Network Error
at createError (createError.js:16)
at XMLHttpRequest.handleError (xhr.js:99)

**Comment by hainamzsd** [comment]
Thank you.

**Comment by Hariom-Singh786** [comment]
> client/src/components/Auth.jsx
> 
> On line 31 const URL = 'https://localhost:5000/auth';
> 
> This generates a network error.
> 
> SHOULD BE : const URL = 'http://localhost:5000/auth';
> 
> Thanks for an awesome tutorial.

thank you brother

**Comment by Hamdysaad20** [comment]
even when i edited the https to http .. i'm still getting this error

**Comment by Hamdysaad20** [comment]
xhr.js:177          POST http://localhost:5000/auth/signup net::ERR_CONNECTION_REFUSED
createError.js:16 Uncaught (in promise) Error: Network Error
    at createError (createError.js:16:1)
    at XMLHttpRequest.handleError (xhr.js:84:1)

**Comment by denv3rr** [comment]
> xhr.js:177 POST http://localhost:5000/auth/signup net::ERR_CONNECTION_REFUSED createError.js:16 Uncaught (in promise) Error: Network Error at createError (createError.js:16:1) at XMLHttpRequest.handleError (xhr.js:84:1)

Hi bro, try replacing your Avatar URL by copying the address of the image to the right of your sign up form and pasting it in the Avatar URL input in the from and submit. See if that works. Looks like the error may be coming from trying to find the image for the avatar. Take care

**Comment by Hamdysaad20** [comment]
> 
![Screenshot 2022-02-25 163353](https://user-images.githubusercontent.com/73494683/155733109-261f1509-b691-45a0-a023-439dcd18f38a.png)
![Screenshot 2022-02-25 163422](https://user-images.githubusercontent.com/73494683/155733114-2395195f-abc7-4bf6-9b05-128ecca39371.png)
![Screenshot 2022-02-25 163438](https://user-images.githubusercontent.com/73494683/155733117-7019c060-039e-466e-9ae8-09b7df93d40a.png)
 ii fetch the data but there is something block it to communicate with the network.

**Comment by Hamdysaad20** [comment]
> > 
> 
> ![Screenshot 2022-02-25 163353](https://user-images.githubusercontent.com/73494683/155733109-261f1509-b691-45a0-a023-439dcd18f38a.png) ![Screenshot 2022-02-25 163422](https://user-images.githubusercontent.com/73494683/155733114-2395195f-abc7-4bf6-9b05-128ecca39371.png) ![Screenshot 2022-02-25 163438](https://user-images.githubusercontent.com/73494683/155733117-7019c060-039e-466e-9ae8-09b7df93d40a.png) ii fetch the data but there is something block it to communicate with the network.

so i think it's a back end part

**Comment by riya1511** [comment]
> > > 
> > 
> > 
> > ![Screenshot 2022-02-25 163353](https://user-images.githubusercontent.com/73494683/155733109-261f1509-b691-45a0-a023-439dcd18f38a.png) ![Screenshot 2022-02-25 163422](https://user-images.githubusercontent.com/73494683/155733114-2395195f-abc7-4bf6-9b05-128ecca39371.png) ![Screenshot 2022-02-25 163438](https://user-images.githubusercontent.com/73494683/155733117-7019c060-039e-466e-9ae8-09b7df93d40a.png)
> 
> i fetch the data but there is something block it to communicate with the network. so i think it's a back end part

Hey.. I was having the same issue, 
While filling the signup form just copy an image URL from free stock image or any reliable URL 
the app will work 😊

**Comment by acoderpath** [comment]
Hi, i'm new in react and has been following the same tutorial. I also ran in into the same issue with "POST http://localhost:5000/auth/true%20?%20%27signup%27%20:%20%27login%27} 404 (Not Found)" and Axios Error. I don't know if anyone has fixed the issue. Thank you

**Comment by DeviousWings** [comment]
Hi, I am new to reactjs. I am having the same problem and your links are broken. I can't get to them. Any help would be appreciated.

**Comment by SomeCoder12** [comment]
I'm still getting the same issue even tho I did everything correct

**Comment by SomeCoder12** [comment]
I am still getting this issue even tho I pasted in the photo URL adress
